version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: OpenCart.Entities.sln
  verbosity: minimal
artifacts:
- path: OpenCart.Entities\bin\Release
  name: OpenCart.Entities
deploy:
- provider: NuGet
  api_key:
    secure: zwQ10VCjmJiJlS7mG++iAJGNxasgTyA5OL/4t/OEbQbZ1SXpBnNtTReslDG18yYF/fst345v8zouCqdO9MWJi5mvGl41sTXqeAWYTUx1IQk=
  artifact: OpenCart.Entities
  on:
    branch: master